version: '3'
services:

  nginx:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - rules
    ports: 
    - "80:80"
    networks:
      - localnet
      - usernet

  entrypoint:
    build:
      context: ../soap-tutorial
      dockerfile: Dockerfile
    environment:
      - USER_URL=http://user:8080
      - VALIDATOR_URL=http://rules:8080
    networks:
      - localnet
      - usernet

  rules:
    build:
      context: ../sb2-rest-tutorial
      dockerfile: Dockerfile
    networks:
      - localnet

  weather:
    build:
      context: ../sb2-weather-tutorial
      dockerfile: Dockerfile
    environment:
      - WEATHER_APPID=${WEATHER_APPID}
    networks:
      - localnet

  user:
    build:
      context: ../sb2-cassandra-tutorial
      dockerfile: Dockerfile
    environment:
      - CONTACT_POINTS=cassandradb
    depends_on:
      - cassandradb
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - database
      - usernet

  cassandradb:
    image: datastax/dse-server
    environment:
      - DS_LICENSE=accept
    networks:
      - database

networks:
    database:
      driver: bridge
    usernet:
      driver: bridge
    localnet:
      driver: bridge
